PATH_LABELS = {
    ('device', 'site'): 'Site',
    ('site',): 'Site',
    ('site', 'group'): 'Site Group',
    ('site', 'region'): 'Region',
    ('region',): 'Region',
    ('region', 'parent'): 'Region',
    ('cluster', 'site'): 'Site',
    ('cluster', '_site'): 'Site',
    ('device_type',): 'Device Type',
    ('device_type', 'manufacturer'): 'Manufacturer',
    ('zabbixconfigurationgroup'): 'Zabbix Configuration Group',
    ('platform',): 'Platform',
    ('role',): 'Role',
    ('cluster',): 'Cluster',
    (
        'cluster',
        'type',
    ): 'Cluster Type',
    ('type',): 'Cluster Type',
}
