# Generated by Django 6.0.7 on 2026-07-30 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nbxsync', '0017_zabbixhostinterface_use_oob_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabbixconfigurationgroupassignment',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'dcim'), ('model', 'virtualdevicecontext')), models.Q(('app_label', 'dcim'), ('model', 'site')), models.Q(('app_label', 'dcim'), ('model', 'sitegroup')), models.Q(('app_label', 'dcim'), ('model', 'region')), models.Q(('app_label', 'dcim'), ('model', 'manufacturer')), models.Q(('app_label', 'dcim'), ('model', 'devicerole')), models.Q(('app_label', 'dcim'), ('model', 'devicetype')), models.Q(('app_label', 'dcim'), ('model', 'platform')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), models.Q(('app_label', 'virtualization'), ('model', 'cluster')), models.Q(('app_label', 'virtualization'), ('model', 'clustertype')), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='zabbixhostgroupassignment',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'dcim'), ('model', 'virtualdevicecontext')), models.Q(('app_label', 'dcim'), ('model', 'site')), models.Q(('app_label', 'dcim'), ('model', 'sitegroup')), models.Q(('app_label', 'dcim'), ('model', 'region')), models.Q(('app_label', 'dcim'), ('model', 'manufacturer')), models.Q(('app_label', 'dcim'), ('model', 'devicerole')), models.Q(('app_label', 'dcim'), ('model', 'devicetype')), models.Q(('app_label', 'dcim'), ('model', 'platform')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), models.Q(('app_label', 'virtualization'), ('model', 'cluster')), models.Q(('app_label', 'virtualization'), ('model', 'clustertype')), _connector='OR'), models.Q(('app_label', 'nbxsync'), ('model', 'zabbixconfigurationgroup')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='zabbixhostinventory',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'dcim'), ('model', 'virtualdevicecontext')), models.Q(('app_label', 'dcim'), ('model', 'site')), models.Q(('app_label', 'dcim'), ('model', 'sitegroup')), models.Q(('app_label', 'dcim'), ('model', 'region')), models.Q(('app_label', 'dcim'), ('model', 'manufacturer')), models.Q(('app_label', 'dcim'), ('model', 'devicerole')), models.Q(('app_label', 'dcim'), ('model', 'devicetype')), models.Q(('app_label', 'dcim'), ('model', 'platform')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), models.Q(('app_label', 'virtualization'), ('model', 'cluster')), models.Q(('app_label', 'virtualization'), ('model', 'clustertype')), _connector='OR'), models.Q(('app_label', 'nbxsync'), ('model', 'zabbixconfigurationgroup')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='zabbixmacroassignment',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'dcim'), ('model', 'virtualdevicecontext')), models.Q(('app_label', 'dcim'), ('model', 'site')), models.Q(('app_label', 'dcim'), ('model', 'sitegroup')), models.Q(('app_label', 'dcim'), ('model', 'region')), models.Q(('app_label', 'dcim'), ('model', 'manufacturer')), models.Q(('app_label', 'dcim'), ('model', 'devicerole')), models.Q(('app_label', 'dcim'), ('model', 'devicetype')), models.Q(('app_label', 'dcim'), ('model', 'platform')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), models.Q(('app_label', 'virtualization'), ('model', 'cluster')), models.Q(('app_label', 'virtualization'), ('model', 'clustertype')), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='zabbixserverassignment',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'dcim'), ('model', 'virtualdevicecontext')), models.Q(('app_label', 'dcim'), ('model', 'site')), models.Q(('app_label', 'dcim'), ('model', 'sitegroup')), models.Q(('app_label', 'dcim'), ('model', 'region')), models.Q(('app_label', 'dcim'), ('model', 'manufacturer')), models.Q(('app_label', 'dcim'), ('model', 'devicerole')), models.Q(('app_label', 'dcim'), ('model', 'devicetype')), models.Q(('app_label', 'dcim'), ('model', 'platform')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), models.Q(('app_label', 'virtualization'), ('model', 'cluster')), models.Q(('app_label', 'virtualization'), ('model', 'clustertype')), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='zabbixtagassignment',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'dcim'), ('model', 'virtualdevicecontext')), models.Q(('app_label', 'dcim'), ('model', 'site')), models.Q(('app_label', 'dcim'), ('model', 'sitegroup')), models.Q(('app_label', 'dcim'), ('model', 'region')), models.Q(('app_label', 'dcim'), ('model', 'manufacturer')), models.Q(('app_label', 'dcim'), ('model', 'devicerole')), models.Q(('app_label', 'dcim'), ('model', 'devicetype')), models.Q(('app_label', 'dcim'), ('model', 'platform')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), models.Q(('app_label', 'virtualization'), ('model', 'cluster')), models.Q(('app_label', 'virtualization'), ('model', 'clustertype')), _connector='OR'), models.Q(('app_label', 'nbxsync'), ('model', 'zabbixconfigurationgroup')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='zabbixtemplateassignment',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'dcim'), ('model', 'virtualdevicecontext')), models.Q(('app_label', 'dcim'), ('model', 'site')), models.Q(('app_label', 'dcim'), ('model', 'sitegroup')), models.Q(('app_label', 'dcim'), ('model', 'region')), models.Q(('app_label', 'dcim'), ('model', 'manufacturer')), models.Q(('app_label', 'dcim'), ('model', 'devicerole')), models.Q(('app_label', 'dcim'), ('model', 'devicetype')), models.Q(('app_label', 'dcim'), ('model', 'platform')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), models.Q(('app_label', 'virtualization'), ('model', 'cluster')), models.Q(('app_label', 'virtualization'), ('model', 'clustertype')), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
