# Generated by Django 5.2.13 on 2026-08-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbxsync', '0017_zabbixtemplaterule_hostgroup_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixtemplaterule',
            name='require_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='zabbixtemplaterule',
            name='role_pattern',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='zabbixtemplaterule',
            name='manufacturer',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional. When set, the Device device_type.manufacturer must match. Empty = any manufacturer. Objects without a manufacturer (e.g. VMs) fail closed when this is set. PROTECT prevents deleting a Manufacturer that would silently widen matching rules.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='zabbixtemplaterules',
                to='dcim.manufacturer',
            ),
        ),
    ]
