# Generated by Django 5.2.13 on 2026-08-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbxsync', '0018_tag_assignment_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixtemplaterule',
            name='require_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='zabbixtemplaterule',
            name='role_pattern',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
