# Generated by Django 5.2.13 on 2026-08-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nbxsync', '0019_zabbixtemplaterule_require_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabbixhostinterface',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'dcim'), ('model', 'virtualdevicecontext')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), _connector='OR'), models.Q(('app_label', 'nbxsync'), ('model', 'zabbixconfigurationgroup')), models.Q(('app_label', 'extras'), ('model', 'tag')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
